version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      # Adicione variáveis do .env conforme necessário
    restart: always
    volumes:
      - .:/app
      # - /app/node_modules
